/* bench.h - cellmark benchmark module interface
 *
 * This is the extension point. To add a new benchmark to cellmark, implement the lifecycle callbacks below in a .c file and export a
 * `const bench_module_t bench_<id>` symbol. The engine discovers it via the registry, groups it with other benches that share its
 * `category`, and dispatches lifecycle callbacks at the right times.
 *
 * See docs/ADDING_A_BENCHMARK.md for the full guide.
 *
 * The two main bench shapes are:
 *
 *   BENCH_KIND_BATCH:      ticks complete quickly and return. The bench
 *                          spawns an SPE group per tick (or runs PPE
 *                          work inline), measures, and updates an
 *                          EMA-smoothed summary. Pi, FFT, N-body, and
 *                          all the per-page benches (PPE compute, EIB
 *                          fabric, DMA, etc.) are batch-kind.
 *
 *   BENCH_KIND_CONTINUOUS: start() spawns long-lived SPE threads that
 *                          keep running. tick() samples shared progress
 *                          counters and computes live rates. stop()
 *                          signals the threads to exit and joins. The
 *                          burn-in bench is continuous-kind.
 *
 * All callbacks are optional (NULL means "do nothing"). The engine
 * never calls tick/render/stop before init succeeded, never calls
 * stop without a matching start, never calls cleanup before stop.
 */

#ifndef CELLMARK_BENCH_H
#define CELLMARK_BENCH_H

#include <stdint.h>

typedef enum {
    BENCH_KIND_BATCH      = 0,
    BENCH_KIND_CONTINUOUS = 1,
    BENCH_KIND_PASSIVE    = 2,   /* no compute, render-only (e.g. sysmon) */
} bench_kind_t;

typedef struct bench_module {
    /* --- identification --- */

    const char  *id;              /* "pi_bbp"; lowercase snake_case;
                                   * used as the logging key and as a
                                   * stable identifier in saved scores */
    const char  *display_name;    /* "Pi (BBP digit extract)" */
    const char  *category;        /* "ppe" / "fabric" / "workload" /
                                   * "burn" / "cell" / "xdr" / "disk";
                                   * benches in the same category form
                                   * one page in the UI */
    bench_kind_t kind;

    /* --- lifecycle (all optional; NULL = noop) --- */

    /* Called once at app startup. tb_freq is the system timebase Hz
     * (79.8 MHz or the actual chip nclk/40 on patched
     * firmware). Return 0 on success, non-zero to permanently
     * disable this bench. */
    int  (*init)(uint64_t tb_freq);

    /* Called when the bench becomes the selected one (user navigated
     * to it). Allocate per-run resources, spawn long-lived threads,
     * etc. The engine never calls start() twice without an
     * intervening stop(). */
    void (*start)(void);

    /* Called every main-loop iteration while the bench is active.
     * BATCH-kind: do the measurement and return (typically 50-500 ms
     * wall time per tick). CONTINUOUS-kind: sample background state. */
    void (*tick)(uint64_t tb_freq);

    /* Called when the bench is deselected, or at app exit. Idempotent.
     * Join threads, free per-run resources. */
    void (*stop)(void);

    /* Called every frame while this bench is the selected one in its
     * category. Write to the dbgfont console via cellDbgFontConsolePrintf.
     * The engine paints the common header (title, clock, time, sysmon)
     * before this is called and the nav footer after, so you only need
     * to render the bench's body. */
    void (*render)(double elapsed_sec);

    /* Called at app shutdown, after stop(). Idempotent. Free any
     * resources allocated in init(). */
    void (*cleanup)(void);

    /* Optional. Called when the user presses an input button (pad event)
     * while this bench is the selected one. The engine handles category
     * navigation (L2/R2) itself; everything else (L1/R1 for variant
     * cycling, TRI, etc.) is forwarded here as a CELL_PAD_BTN_OFFSET
     * pair. Multi-variant benches (PPE, EIB, DMA, DISK with internal
     * sub-benches) use this to cycle their variant. */
    void (*input)(uint16_t btns1, uint16_t btns2);
} bench_module_t;

/* The registry. Generated by tools/build.py from the benches discovered
 * at build time. NULL-terminated, ordered by category-then-declaration
 * so UI navigation is deterministic. */
extern const bench_module_t *const cellmark_bench_registry[];

/* Declaration convention: each bench's .c file ends with
 *
 *   const bench_module_t bench_<id> = {
 *       .id           = "<id>",
 *       .display_name = "...",
 *       .category     = "...",
 *       .kind         = BENCH_KIND_BATCH,
 *       .init         = ...,
 *       .tick         = ...,
 *       .render       = ...,
 *   };
 *
 * where <id> matches the .id string and the parent folder name under
 * benches/. build.py greps for `bench_<id>` symbols, generates the
 * registry, and complains if it finds a mismatch. */

#endif /* CELLMARK_BENCH_H */